// Code generated by protoc-gen-go. DO NOT EDIT.
// source: demo.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SearchReq struct {
	Q                    string   `protobuf:"bytes,1,opt,name=q,proto3" json:"q,omitempty"`
	Params               []string `protobuf:"bytes,2,rep,name=params,proto3" json:"params,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchReq) Reset()         { *m = SearchReq{} }
func (m *SearchReq) String() string { return proto.CompactTextString(m) }
func (*SearchReq) ProtoMessage()    {}
func (*SearchReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca53982754088a9d, []int{0}
}

func (m *SearchReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchReq.Unmarshal(m, b)
}
func (m *SearchReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchReq.Marshal(b, m, deterministic)
}
func (m *SearchReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchReq.Merge(m, src)
}
func (m *SearchReq) XXX_Size() int {
	return xxx_messageInfo_SearchReq.Size(m)
}
func (m *SearchReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchReq.DiscardUnknown(m)
}

var xxx_messageInfo_SearchReq proto.InternalMessageInfo

func (m *SearchReq) GetQ() string {
	if m != nil {
		return m.Q
	}
	return ""
}

func (m *SearchReq) GetParams() []string {
	if m != nil {
		return m.Params
	}
	return nil
}

func init() {
	proto.RegisterType((*SearchReq)(nil), "model.other.thing.SearchReq")
}

func init() { proto.RegisterFile("demo.proto", fileDescriptor_ca53982754088a9d) }

var fileDescriptor_ca53982754088a9d = []byte{
	// 112 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x49, 0xcd, 0xcd,
	0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0xcc, 0xcd, 0x4f, 0x49, 0xcd, 0xd1, 0xcb, 0x2f,
	0xc9, 0x48, 0x2d, 0xd2, 0x2b, 0xc9, 0xc8, 0xcc, 0x4b, 0x57, 0x32, 0xe4, 0xe2, 0x0c, 0x4e, 0x4d,
	0x2c, 0x4a, 0xce, 0x08, 0x4a, 0x2d, 0x14, 0xe2, 0xe1, 0x62, 0x2c, 0x94, 0x60, 0x54, 0x60, 0xd4,
	0xe0, 0x0c, 0x62, 0x2c, 0x14, 0x12, 0xe3, 0x62, 0x2b, 0x48, 0x2c, 0x4a, 0xcc, 0x2d, 0x96, 0x60,
	0x52, 0x60, 0xd6, 0xe0, 0x0c, 0x82, 0xf2, 0x9c, 0xd8, 0xa3, 0x58, 0xc1, 0xe6, 0x24, 0xb1, 0x81,
	0x4d, 0x35, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x12, 0x1c, 0xfd, 0x18, 0x63, 0x00, 0x00, 0x00,
}
