// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: demo.proto

#include "demo.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

namespace model {
namespace other {
namespace thing {
class SearchReqDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<SearchReq> _instance;
} _SearchReq_default_instance_;
}  // namespace thing
}  // namespace other
}  // namespace model
static void InitDefaultsSearchReq_demo_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::model::other::thing::_SearchReq_default_instance_;
    new (ptr) ::model::other::thing::SearchReq();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::model::other::thing::SearchReq::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_SearchReq_demo_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsSearchReq_demo_2eproto}, {}};

void InitDefaults_demo_2eproto() {
  ::google::protobuf::internal::InitSCC(&scc_info_SearchReq_demo_2eproto.base);
}

::google::protobuf::Metadata file_level_metadata_demo_2eproto[1];
constexpr ::google::protobuf::EnumDescriptor const** file_level_enum_descriptors_demo_2eproto = nullptr;
constexpr ::google::protobuf::ServiceDescriptor const** file_level_service_descriptors_demo_2eproto = nullptr;

const ::google::protobuf::uint32 TableStruct_demo_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::model::other::thing::SearchReq, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::model::other::thing::SearchReq, q_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::model::other::thing::SearchReq)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::model::other::thing::_SearchReq_default_instance_),
};

::google::protobuf::internal::AssignDescriptorsTable assign_descriptors_table_demo_2eproto = {
  {}, AddDescriptors_demo_2eproto, "demo.proto", schemas,
  file_default_instances, TableStruct_demo_2eproto::offsets,
  file_level_metadata_demo_2eproto, 1, file_level_enum_descriptors_demo_2eproto, file_level_service_descriptors_demo_2eproto,
};

const char descriptor_table_protodef_demo_2eproto[] =
  "\n\ndemo.proto\022\021model.other.thing\"\026\n\tSearc"
  "hReq\022\t\n\001q\030\001 \001(\tB\007Z\005modelb\006proto3"
  ;
::google::protobuf::internal::DescriptorTable descriptor_table_demo_2eproto = {
  false, InitDefaults_demo_2eproto, 
  descriptor_table_protodef_demo_2eproto,
  "demo.proto", &assign_descriptors_table_demo_2eproto, 72,
};

void AddDescriptors_demo_2eproto() {
  static constexpr ::google::protobuf::internal::InitFunc deps[1] =
  {
  };
 ::google::protobuf::internal::AddDescriptors(&descriptor_table_demo_2eproto, deps, 0);
}

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_demo_2eproto = []() { AddDescriptors_demo_2eproto(); return true; }();
namespace model {
namespace other {
namespace thing {

// ===================================================================

void SearchReq::InitAsDefaultInstance() {
}
class SearchReq::HasBitSetters {
 public:
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SearchReq::kQFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SearchReq::SearchReq()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:model.other.thing.SearchReq)
}
SearchReq::SearchReq(const SearchReq& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  q_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.q().size() > 0) {
    q_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.q_);
  }
  // @@protoc_insertion_point(copy_constructor:model.other.thing.SearchReq)
}

void SearchReq::SharedCtor() {
  ::google::protobuf::internal::InitSCC(
      &scc_info_SearchReq_demo_2eproto.base);
  q_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

SearchReq::~SearchReq() {
  // @@protoc_insertion_point(destructor:model.other.thing.SearchReq)
  SharedDtor();
}

void SearchReq::SharedDtor() {
  q_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void SearchReq::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const SearchReq& SearchReq::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_SearchReq_demo_2eproto.base);
  return *internal_default_instance();
}


void SearchReq::Clear() {
// @@protoc_insertion_point(message_clear_start:model.other.thing.SearchReq)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  q_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* SearchReq::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<SearchReq*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // string q = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 10) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("model.other.thing.SearchReq.q");
        object = msg->mutable_q();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
string_till_end:
  static_cast<::std::string*>(object)->clear();
  static_cast<::std::string*>(object)->reserve(size);
  goto len_delim_till_end;
len_delim_till_end:
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                               {parser_till_end, object}, size);
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool SearchReq::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:model.other.thing.SearchReq)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string q = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (10 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_q()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->q().data(), static_cast<int>(this->q().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "model.other.thing.SearchReq.q"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:model.other.thing.SearchReq)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:model.other.thing.SearchReq)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void SearchReq::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:model.other.thing.SearchReq)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string q = 1;
  if (this->q().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->q().data(), static_cast<int>(this->q().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "model.other.thing.SearchReq.q");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->q(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:model.other.thing.SearchReq)
}

::google::protobuf::uint8* SearchReq::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:model.other.thing.SearchReq)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string q = 1;
  if (this->q().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->q().data(), static_cast<int>(this->q().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "model.other.thing.SearchReq.q");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->q(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:model.other.thing.SearchReq)
  return target;
}

size_t SearchReq::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:model.other.thing.SearchReq)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string q = 1;
  if (this->q().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->q());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SearchReq::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:model.other.thing.SearchReq)
  GOOGLE_DCHECK_NE(&from, this);
  const SearchReq* source =
      ::google::protobuf::DynamicCastToGenerated<SearchReq>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:model.other.thing.SearchReq)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:model.other.thing.SearchReq)
    MergeFrom(*source);
  }
}

void SearchReq::MergeFrom(const SearchReq& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:model.other.thing.SearchReq)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.q().size() > 0) {

    q_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.q_);
  }
}

void SearchReq::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:model.other.thing.SearchReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SearchReq::CopyFrom(const SearchReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:model.other.thing.SearchReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SearchReq::IsInitialized() const {
  return true;
}

void SearchReq::Swap(SearchReq* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SearchReq::InternalSwap(SearchReq* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  q_.Swap(&other->q_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
}

::google::protobuf::Metadata SearchReq::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_demo_2eproto);
  return ::file_level_metadata_demo_2eproto[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace thing
}  // namespace other
}  // namespace model
namespace google {
namespace protobuf {
template<> PROTOBUF_NOINLINE ::model::other::thing::SearchReq* Arena::CreateMaybeMessage< ::model::other::thing::SearchReq >(Arena* arena) {
  return Arena::CreateInternal< ::model::other::thing::SearchReq >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
