# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: demo.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("demo.proto", :syntax => :proto3) do
    add_message "model.other.thing.SearchReq" do
      optional :q, :string, 1
    end
  end
end

module Model
  module Other
    module Thing
      SearchReq = Google::Protobuf::DescriptorPool.generated_pool.lookup("model.other.thing.SearchReq").msgclass
    end
  end
end
