// Code generated by protoc-gen-go. DO NOT EDIT.
// source: demo.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type From int32

const (
	From_Cache   From = 0
	From_Current From = 1
)

var From_name = map[int32]string{
	0: "Cache",
	1: "Current",
}

var From_value = map[string]int32{
	"Cache":   0,
	"Current": 1,
}

func (x From) String() string {
	return proto.EnumName(From_name, int32(x))
}

func (From) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ca53982754088a9d, []int{0}
}

type SearchReq struct {
	Q                    string            `protobuf:"bytes,1,opt,name=q,proto3" json:"q,omitempty"`
	Params               map[string]string `protobuf:"bytes,2,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Id                   int64             `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SearchReq) Reset()         { *m = SearchReq{} }
func (m *SearchReq) String() string { return proto.CompactTextString(m) }
func (*SearchReq) ProtoMessage()    {}
func (*SearchReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca53982754088a9d, []int{0}
}

func (m *SearchReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchReq.Unmarshal(m, b)
}
func (m *SearchReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchReq.Marshal(b, m, deterministic)
}
func (m *SearchReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchReq.Merge(m, src)
}
func (m *SearchReq) XXX_Size() int {
	return xxx_messageInfo_SearchReq.Size(m)
}
func (m *SearchReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchReq.DiscardUnknown(m)
}

var xxx_messageInfo_SearchReq proto.InternalMessageInfo

func (m *SearchReq) GetQ() string {
	if m != nil {
		return m.Q
	}
	return ""
}

func (m *SearchReq) GetParams() map[string]string {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *SearchReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type SearchResp struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Ans                  string   `protobuf:"bytes,2,opt,name=ans,proto3" json:"ans,omitempty"`
	Source               From     `protobuf:"varint,3,opt,name=source,proto3,enum=model.other.thing.From" json:"source,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchResp) Reset()         { *m = SearchResp{} }
func (m *SearchResp) String() string { return proto.CompactTextString(m) }
func (*SearchResp) ProtoMessage()    {}
func (*SearchResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca53982754088a9d, []int{1}
}

func (m *SearchResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchResp.Unmarshal(m, b)
}
func (m *SearchResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchResp.Marshal(b, m, deterministic)
}
func (m *SearchResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchResp.Merge(m, src)
}
func (m *SearchResp) XXX_Size() int {
	return xxx_messageInfo_SearchResp.Size(m)
}
func (m *SearchResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchResp.DiscardUnknown(m)
}

var xxx_messageInfo_SearchResp proto.InternalMessageInfo

func (m *SearchResp) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SearchResp) GetAns() string {
	if m != nil {
		return m.Ans
	}
	return ""
}

func (m *SearchResp) GetSource() From {
	if m != nil {
		return m.Source
	}
	return From_Cache
}

func init() {
	proto.RegisterEnum("model.other.thing.From", From_name, From_value)
	proto.RegisterType((*SearchReq)(nil), "model.other.thing.SearchReq")
	proto.RegisterMapType((map[string]string)(nil), "model.other.thing.SearchReq.ParamsEntry")
	proto.RegisterType((*SearchResp)(nil), "model.other.thing.SearchResp")
}

func init() { proto.RegisterFile("demo.proto", fileDescriptor_ca53982754088a9d) }

var fileDescriptor_ca53982754088a9d = []byte{
	// 254 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x41, 0x4b, 0xf4, 0x30,
	0x10, 0x86, 0xbf, 0xa4, 0x5f, 0xbb, 0x74, 0x2a, 0x4b, 0x0d, 0x82, 0xc5, 0x83, 0x94, 0x3d, 0x15,
	0x0f, 0x11, 0xd6, 0x8b, 0x7a, 0x12, 0x17, 0x3d, 0x4b, 0xbc, 0x79, 0x91, 0xd8, 0x0e, 0xb6, 0xb8,
	0x6d, 0xda, 0x69, 0x2a, 0xec, 0x1f, 0xf2, 0x77, 0x4a, 0x63, 0x56, 0x04, 0xbd, 0xcd, 0x84, 0xf7,
	0x79, 0xde, 0x30, 0x00, 0x15, 0xb6, 0x46, 0xf6, 0x64, 0xac, 0x11, 0x87, 0xad, 0xa9, 0x70, 0x2b,
	0x8d, 0xad, 0x91, 0xa4, 0xad, 0x9b, 0xee, 0x75, 0xf5, 0xc1, 0x20, 0x7e, 0x44, 0x4d, 0x65, 0xad,
	0x70, 0x10, 0x07, 0xc0, 0x86, 0x8c, 0xe5, 0xac, 0x88, 0x15, 0x1b, 0xc4, 0x0d, 0x44, 0xbd, 0x26,
	0xdd, 0x8e, 0x19, 0xcf, 0x83, 0x22, 0x59, 0x17, 0xf2, 0x17, 0x2f, 0xbf, 0x59, 0xf9, 0xe0, 0xa2,
	0x77, 0x9d, 0xa5, 0x9d, 0xf2, 0x9c, 0x58, 0x02, 0x6f, 0xaa, 0x2c, 0xc8, 0x59, 0x11, 0x28, 0xde,
	0x54, 0x27, 0x57, 0x90, 0xfc, 0x88, 0x89, 0x14, 0x82, 0x37, 0xdc, 0xf9, 0xc2, 0x79, 0x14, 0x47,
	0x10, 0xbe, 0xeb, 0xed, 0x84, 0x19, 0x77, 0x6f, 0x5f, 0xcb, 0x35, 0xbf, 0x64, 0xab, 0x67, 0x80,
	0x7d, 0xd7, 0xd8, 0x7b, 0x31, 0xdb, 0x8b, 0x67, 0x93, 0xee, 0x46, 0x4f, 0xcd, 0xa3, 0x38, 0x87,
	0x68, 0x34, 0x13, 0x95, 0xe8, 0xea, 0x97, 0xeb, 0xe3, 0x3f, 0x3e, 0x7f, 0x4f, 0xa6, 0x55, 0x3e,
	0x76, 0x76, 0x0a, 0xff, 0xe7, 0x5d, 0xc4, 0x10, 0x6e, 0x74, 0x59, 0x63, 0xfa, 0x4f, 0x24, 0xb0,
	0xd8, 0x4c, 0x44, 0xd8, 0xd9, 0x94, 0xdd, 0x2e, 0x9e, 0x42, 0x67, 0x78, 0x89, 0xdc, 0x31, 0x2f,
	0x3e, 0x03, 0x00, 0x00, 0xff, 0xff, 0xcf, 0x84, 0x3f, 0x14, 0x5a, 0x01, 0x00, 0x00,
}
