// Code generated by protoc-gen-go. DO NOT EDIT.
// source: demo.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Search_Resp_From int32

const (
	Search_Resp_Cache   Search_Resp_From = 0
	Search_Resp_Current Search_Resp_From = 1
)

var Search_Resp_From_name = map[int32]string{
	0: "Cache",
	1: "Current",
}

var Search_Resp_From_value = map[string]int32{
	"Cache":   0,
	"Current": 1,
}

func (x Search_Resp_From) String() string {
	return proto.EnumName(Search_Resp_From_name, int32(x))
}

func (Search_Resp_From) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ca53982754088a9d, []int{0, 1, 0}
}

type Search struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Search) Reset()         { *m = Search{} }
func (m *Search) String() string { return proto.CompactTextString(m) }
func (*Search) ProtoMessage()    {}
func (*Search) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca53982754088a9d, []int{0}
}

func (m *Search) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Search.Unmarshal(m, b)
}
func (m *Search) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Search.Marshal(b, m, deterministic)
}
func (m *Search) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Search.Merge(m, src)
}
func (m *Search) XXX_Size() int {
	return xxx_messageInfo_Search.Size(m)
}
func (m *Search) XXX_DiscardUnknown() {
	xxx_messageInfo_Search.DiscardUnknown(m)
}

var xxx_messageInfo_Search proto.InternalMessageInfo

type Search_Req struct {
	Q                    string            `protobuf:"bytes,1,opt,name=q,proto3" json:"q,omitempty"`
	Params               map[string]string `protobuf:"bytes,2,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Id                   int64             `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Search_Req) Reset()         { *m = Search_Req{} }
func (m *Search_Req) String() string { return proto.CompactTextString(m) }
func (*Search_Req) ProtoMessage()    {}
func (*Search_Req) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca53982754088a9d, []int{0, 0}
}

func (m *Search_Req) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Search_Req.Unmarshal(m, b)
}
func (m *Search_Req) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Search_Req.Marshal(b, m, deterministic)
}
func (m *Search_Req) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Search_Req.Merge(m, src)
}
func (m *Search_Req) XXX_Size() int {
	return xxx_messageInfo_Search_Req.Size(m)
}
func (m *Search_Req) XXX_DiscardUnknown() {
	xxx_messageInfo_Search_Req.DiscardUnknown(m)
}

var xxx_messageInfo_Search_Req proto.InternalMessageInfo

func (m *Search_Req) GetQ() string {
	if m != nil {
		return m.Q
	}
	return ""
}

func (m *Search_Req) GetParams() map[string]string {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *Search_Req) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Search_Resp struct {
	Id                   int64            `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Ans                  string           `protobuf:"bytes,2,opt,name=ans,proto3" json:"ans,omitempty"`
	Source               Search_Resp_From `protobuf:"varint,3,opt,name=source,proto3,enum=model.other.thing.Search_Resp_From" json:"source,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Search_Resp) Reset()         { *m = Search_Resp{} }
func (m *Search_Resp) String() string { return proto.CompactTextString(m) }
func (*Search_Resp) ProtoMessage()    {}
func (*Search_Resp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca53982754088a9d, []int{0, 1}
}

func (m *Search_Resp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Search_Resp.Unmarshal(m, b)
}
func (m *Search_Resp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Search_Resp.Marshal(b, m, deterministic)
}
func (m *Search_Resp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Search_Resp.Merge(m, src)
}
func (m *Search_Resp) XXX_Size() int {
	return xxx_messageInfo_Search_Resp.Size(m)
}
func (m *Search_Resp) XXX_DiscardUnknown() {
	xxx_messageInfo_Search_Resp.DiscardUnknown(m)
}

var xxx_messageInfo_Search_Resp proto.InternalMessageInfo

func (m *Search_Resp) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Search_Resp) GetAns() string {
	if m != nil {
		return m.Ans
	}
	return ""
}

func (m *Search_Resp) GetSource() Search_Resp_From {
	if m != nil {
		return m.Source
	}
	return Search_Resp_Cache
}

func init() {
	proto.RegisterEnum("model.other.thing.Search_Resp_From", Search_Resp_From_name, Search_Resp_From_value)
	proto.RegisterType((*Search)(nil), "model.other.thing.Search")
	proto.RegisterType((*Search_Req)(nil), "model.other.thing.Search.Req")
	proto.RegisterMapType((map[string]string)(nil), "model.other.thing.Search.Req.ParamsEntry")
	proto.RegisterType((*Search_Resp)(nil), "model.other.thing.Search.Resp")
}

func init() { proto.RegisterFile("demo.proto", fileDescriptor_ca53982754088a9d) }

var fileDescriptor_ca53982754088a9d = []byte{
	// 266 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0xbd, 0x4a, 0xc4, 0x40,
	0x14, 0x85, 0xbd, 0x93, 0x4d, 0x96, 0xbd, 0x91, 0x25, 0x0e, 0x16, 0x21, 0x85, 0x84, 0xb5, 0x89,
	0xcd, 0x14, 0x6b, 0xe3, 0x4f, 0xa5, 0x8b, 0xd6, 0x32, 0x76, 0x76, 0x63, 0x72, 0x31, 0xc1, 0x4d,
	0x26, 0x99, 0x24, 0xc2, 0x3e, 0x80, 0x0f, 0xe2, 0x3b, 0xf8, 0x80, 0x92, 0xd9, 0x11, 0x04, 0x61,
	0xbb, 0x73, 0x86, 0x73, 0xbe, 0x33, 0x5c, 0xc4, 0x82, 0x6a, 0x2d, 0x5a, 0xa3, 0x07, 0xcd, 0x4f,
	0x6a, 0x5d, 0xd0, 0x56, 0xe8, 0xa1, 0x24, 0x23, 0x86, 0xb2, 0x6a, 0xde, 0x56, 0xdf, 0x0c, 0x83,
	0x67, 0x52, 0x26, 0x2f, 0x93, 0x2f, 0x40, 0x4f, 0x52, 0xc7, 0x8f, 0x11, 0xba, 0x18, 0x52, 0xc8,
	0x16, 0x12, 0x3a, 0x7e, 0x87, 0x41, 0xab, 0x8c, 0xaa, 0xfb, 0x98, 0xa5, 0x5e, 0x16, 0xae, 0x2f,
	0xc4, 0x3f, 0x88, 0xd8, 0x03, 0x84, 0xa4, 0x4e, 0x3c, 0xd9, 0xec, 0x43, 0x33, 0x98, 0x9d, 0x74,
	0x45, 0xbe, 0x44, 0x56, 0x15, 0xb1, 0x97, 0x42, 0xe6, 0x49, 0x56, 0x15, 0xc9, 0x35, 0x86, 0x7f,
	0x62, 0x3c, 0x42, 0xef, 0x9d, 0x76, 0x6e, 0x71, 0x92, 0xfc, 0x14, 0xfd, 0x0f, 0xb5, 0x1d, 0x29,
	0x66, 0xf6, 0x6d, 0x6f, 0x6e, 0xd8, 0x15, 0x24, 0x9f, 0x80, 0x33, 0x49, 0x7d, 0xeb, 0x98, 0xf0,
	0xcb, 0x9c, 0x20, 0xaa, 0xe9, 0x5d, 0x61, 0x92, 0xfc, 0x16, 0x83, 0x5e, 0x8f, 0x26, 0x27, 0xbb,
	0xbc, 0x5c, 0x9f, 0x1f, 0xfa, 0x78, 0xdf, 0x8a, 0x47, 0xa3, 0x6b, 0xe9, 0x2a, 0xab, 0x33, 0x9c,
	0x4d, 0x9e, 0x2f, 0xd0, 0xdf, 0xa8, 0xbc, 0xa4, 0xe8, 0x88, 0x87, 0x38, 0xdf, 0x8c, 0xc6, 0x50,
	0x33, 0x44, 0x70, 0x3f, 0x7f, 0xf1, 0x2d, 0xed, 0x35, 0xb0, 0x97, 0xbd, 0xfc, 0x09, 0x00, 0x00,
	0xff, 0xff, 0xad, 0x1a, 0x87, 0xcc, 0x67, 0x01, 0x00, 0x00,
}
