### auth with user and password
# @name login
POST {{$dotenv API_URL}}/admins/auth-with-password
Content-Type: application/json

{
  "identity": "{{$dotenv ADMIN_USERNAME}}",
  "password": "{{$dotenv ADMIN_PASSWORD}}"
}

# save JWT
@authToken = {{login.response.body.$.token}}

### get ALL of our unordered carts
GET {{$dotenv COLLECTIONS_URL}}/carts/records
Authorization: Bearer {{authToken}}

### get ALL of our ordered carts
GET {{$dotenv COLLECTIONS_URL}}/carts_view/records
Authorization: Bearer {{authToken}}
